baseURL          =  "http://ecochallenge.buffalo-coders.org/"
languageCode     =  "en-us"
title            =  "Buffalo Cool Roof Project"
disableKinds     =  ["RSS", "taxonomy", "taxonomyTerm"]
enableRobotsTXT  =  "true"
